### ISSUE TITLE
[Java] serialization support for optionals

### ISSUE THREAD

**Issue by chaokunyang** [apache/fory#133]
**Is your feature request related to a problem? Please describe.**
Add serialization support for java.util.OptionalXXX

**Comment by JackyAnn** [comment]
java.util.Optional is not supported for cross-language serialization.

However, the documentation clearly states that java.util.Optional is supported for xlang.



https://fory.apache.org/docs/specification/xlang_serialization_spec#language-specific-considerations
<img width="1712" height="536" alt="Image" src="https://github.com/user-attachments/assets/c7396f4d-ebf5-44b2-a30d-c0629a876d5c" />


@chaokunyang
