### ISSUE TITLE
[Question] is content type defined and standardized? 

### ISSUE THREAD

**Issue by JackyAnn** [apache/fory#1951]
### Question

Is the content type defined and standardized?
I didn't find any information in the documentation.

**Comment by chaokunyang** [comment]
@JackyAnn could you share more details? I don't understand what you mean `content type`

**Comment by JackyAnn** [comment]
http content type
For example, the content type for json is application/json.
The content type for protobuf is application/x-protobuf.

**Comment by chaokunyang** [comment]
This is not related to Fury. It's parsed by a http server. Depending on your http framework used, you may need to post this issue to their community such as spring/akka.

For example, quarkus supports application/fury in https://github.com/quarkiverse/quarkus-fury/pull/31
